### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by cpkang** [daodaolee/vuepress-plugin-awesome-musicplayer#3]
在使用类似图床链接引入音乐连接后 可以显示样式但是不能播放 控制台报跨域问题
![image](https://user-images.githubusercontent.com/104294722/175249839-eabe23c8-6ba5-4cba-a00a-da807d7b45d5.png)
请问如何解决

**Comment by cpkang** [comment]
请问添加本地文件的话 路径应该怎么填呢

**Comment by cpkang** [comment]
使用 本地文件的话可以了 路径我是这样填的
![image](https://user-images.githubusercontent.com/104294722/175280266-7c2bcadb-e7da-4b94-bfad-fe280c53d601.png)
不过就是没有那个可视化功能
![image](https://user-images.githubusercontent.com/104294722/175280372-f768c596-31a2-4c04-b7fb-44b449a7d927.png)

**Comment by cpkang** [comment]
> 使用本地文件的话 就可以了 ![图片](https://user-images.githubusercontent.com/104294722/175280266-7c2bcadb-e7da-4b94-bfad-fe280c53d601.png) ![图片](https://user-images.githubusercontent.com/104294722/175280372-f768c596-31a2-4c04-b7fb-44b449a7d927.png)

原来也可以 点第三个切换按钮就可以

**Comment by daodaolee** [comment]
如果是跨域问题的话，把音乐放到不跨域的服务器上访问，我是放到了腾讯云的存储桶做个预览用。
